### ISSUE TITLE
ApplicationInsights Exception problem in RenderViewToString<TModel>(string name, TModel model) method

### ISSUE THREAD

**Issue by sunilrav** [aspnet/Entropy#183]
I am getting this exception when I try `RenderViewToString` in my code. The sample runs fine. 

**No service for type 'Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration' has been registered.**

Any Idea whats going on? The only difference is I am using net461 but the sample is using net451.

**Comment by hishamco** [comment]
@sunilrav could you please open the issue in the https://github.com/Microsoft/ApplicationInsights-aspnetcore repo, I'm not quite sure why you open it here?!!

**Comment by ajaybhargavb** [comment]
@sunilrav, if you are trying to render a view that uses a service, make sure you register that service in your service container. See how the sample registers EmailReportGenerator because it is used in a view https://github.com/aspnet/Entropy/blob/dev/samples/Mvc.RenderViewToString/Program.cs#L36

**Comment by Eilon** [comment]
Hi, this issue is being closed because this repo contains only unofficial samples and tests, and is not otherwise regularly maintained. If you're having an issue with ASP.NET Core or EF Core, please log a new issue in the appropriate product repo (or if you're not sure where, the https://github.com/aspnet/Home/issues repo).
