### ISSUE TITLE
Fix or remove WebListener test variants

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Entropy#188]
Some of the functional tests have a variant that claims to test WebListener. However, none of the sample apps are set up to dynamically toggle between servers in Main. They still use an old mechanic where you used to be able to toggle via a simple config string. This hasn't worked for almost a year, you have to explicitly call UseKestrel or UseHttpSys. (see MusicStore).

See the outdated comment in most of the Startup.Main methods: "We set the server by name before default args so that command line arguments can override it. This is used to allow deployers to choose the server for testing."

WebListener isn't a meaningful variation for most of these test scenarios, we may be able to just remove those variants (and the comment).
https://github.com/aspnet/Entropy/search?p=1&q=weblistener&utf8=%E2%9C%93

**Comment by Eilon** [comment]
Please remove any useless/dead tests.

**Comment by muratg** [comment]
Bringing this back to triage.

**Comment by Eilon** [comment]
Hi, this issue is being closed because this repo contains only unofficial samples and tests, and is not otherwise regularly maintained. If you're having an issue with ASP.NET Core or EF Core, please log a new issue in the appropriate product repo (or if you're not sure where, the https://github.com/aspnet/Home/issues repo).
