### ISSUE TITLE
Antiforgery.Angular1 example not applicable to the Real World

### ISSUE THREAD

**Issue by itanex** [aspnet/Entropy#200]
The example in **Antiforgery.Angular1** places the functionality of the '/api/items' route directly into the startup and removes the separation of concerns between middleware and controller. This is not a real world example.

In MVC using an Antiforgery token is simple, each page/controller action would drop down a token in the form and it is all good. In WebApi, in context of Angular, however, the example should demonstrate setting up the cookie and header as it is outlined in the [$http Documentation](https://docs.angularjs.org/api/ng/service/$http#cross-site-request-forgery-xsrf-protection) so that angular can handle is properly and WebApi endpoints can continue to use the built in facilities for validating a token. With WebApi there will also be a need to illustrate how to place the XSRF token into a cookie so that Angular will properly pick it up.

- [Should outline how to set the XSRF Header] 
- [Should outline how to set the XSRF Cookie] 
- [How to write the XSRF into the requests through a Middleware solution]

**Comment by Eilon** [comment]
Hi, this issue is being closed because this repo contains only unofficial samples and tests, and is not otherwise regularly maintained. If you're having an issue with ASP.NET Core or EF Core, please log a new issue in the appropriate product repo (or if you're not sure where, the https://github.com/aspnet/Home/issues repo).
