### ISSUE TITLE
Clean up compilation warnings

### ISSUE THREAD

**Issue by dougbu** [aspnet/Entropy#202]
Entropy builds for .NET Core App emit warnings such as

> CSC : warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'System.Resources.ResourceManager' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [C:\dd\dnx\Universe\Entropy\samples\Localization.CustomResourceManager\Localization.CustomResourceManager.csproj]
obj\Debug\netcoreapp1.1\zh\Localization.CustomResourceManager.resources.cs(15,12): warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'System.Resources.ResourceManager' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [C:\dd\dnx\Universe\Entropy\samples\Localization.CustomResourceManager\Localization.CustomResourceManager.csproj]

Clean these up once that is possible. dotnet/sdk#954 currently blocks fixing this issue.

**Comment by Eilon** [comment]
Hi, this issue is being closed because this repo contains only unofficial samples and tests, and is not otherwise regularly maintained. If you're having an issue with ASP.NET Core or EF Core, please log a new issue in the appropriate product repo (or if you're not sure where, the https://github.com/aspnet/Home/issues repo).
