### ISSUE TITLE
Mvc.RenderViewToString needs to be updated

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Entropy#222]
This sample needs to be revisited to check if it can use stuff from new Razor, mainly RazorTemplateEngine.

cc' @Eilon @pranavkm

**Comment by pranavkm** [comment]
@ajaybhargavb can this be closed?

**Comment by Eilon** [comment]
Hi, this issue is being closed because this repo contains only unofficial samples and tests, and is not otherwise regularly maintained. If you're having an issue with ASP.NET Core or EF Core, please log a new issue in the appropriate product repo (or if you're not sure where, the https://github.com/aspnet/Home/issues repo).
