### ISSUE TITLE
dev/samples/Builder.Filtering.Web/Startup.cs calls next after writing to response

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Entropy#227]
See [this code](https://github.com/aspnet/Entropy/blob/dev/samples/Builder.Filtering.Web/Startup.cs#L29-L31).

Is it possible to use logging to make the sample valid - or at least add a comment saying don't do this in production - this is a sample on filters?

**Comment by Eilon** [comment]
Hi, this issue is being closed because this repo contains only unofficial samples and tests, and is not otherwise regularly maintained. If you're having an issue with ASP.NET Core or EF Core, please log a new issue in the appropriate product repo (or if you're not sure where, the https://github.com/aspnet/Home/issues repo).
