### ISSUE TITLE
Localization Problem

### ISSUE THREAD

**Issue by thecobe** [aspnet/Entropy#232]
Hi
i'm trying to use your localization example inside Localization.StarterWeb project
It's perfect solution for my site 
I copy exactly your code but nothing happens
Can you help me please?
How can i send you my code?
thanks
bye
Mark

**Comment by Eilon** [comment]
Hi, this issue is being closed because this repo contains only unofficial samples and tests, and is not otherwise regularly maintained. If you're having an issue with ASP.NET Core or EF Core, please log a new issue in the appropriate product repo (or if you're not sure where, the https://github.com/aspnet/Home/issues repo).
