### ISSUE TITLE
Extract common code in sample csproj to samples.props or common.props

### ISSUE THREAD

**Issue by mikeharder** [aspnet/Entropy#243]
@NTaylorMullen suggested that the common code in the sample csproj files (like the below) should be extracted to a samples.props or common.props:

```
<ItemGroup Condition=" '$(TargetFramework)' == 'net461' ">
  <PackageReference Include="NETStandard.Library.NETFramework" Version="$(NETStandardLibraryNETFrameworkVersion)" />
</ItemGroup>
```

**Comment by NTaylorMullen** [comment]
Note: it's already in common.props, the alternative would to be just to use common.props (assuming it doesn't pollute the sample).

**Comment by Eilon** [comment]
Hi, this issue is being closed because this repo contains only unofficial samples and tests, and is not otherwise regularly maintained. If you're having an issue with ASP.NET Core or EF Core, please log a new issue in the appropriate product repo (or if you're not sure where, the https://github.com/aspnet/Home/issues repo).
