### ISSUE TITLE
Remove unnecessary file "samples/Owin.Nowin.HelloWorld/web.config"

### ISSUE THREAD

**Issue by mikeharder** [aspnet/Entropy#244]
@natemcmaster suggested we don't need this file in the project anymore unless we need to customize it, which it doesn't appear we are doing here. Microsoft.NET.Sdk.Web will generate this file.

**Comment by Eilon** [comment]
Hi, this issue is being closed because this repo contains only unofficial samples and tests, and is not otherwise regularly maintained. If you're having an issue with ASP.NET Core or EF Core, please log a new issue in the appropriate product repo (or if you're not sure where, the https://github.com/aspnet/Home/issues repo).
