### ISSUE TITLE
solution way to big, neverending loading

### ISSUE THREAD

**Issue by samarmir** [aspnet/Entropy#274]
The solution with all its projects is way to big, the projects just keep loading and loading.

**Comment by Eilon** [comment]
Hi, this issue is being closed because this repo contains only unofficial samples and tests, and is not otherwise regularly maintained. If you're having an issue with ASP.NET Core or EF Core, please log a new issue in the appropriate product repo (or if you're not sure where, the https://github.com/aspnet/Home/issues repo).

If this is an issue with Visual Studio, please use VS's built in "Report a Problem" feature.
