### ISSUE TITLE
CompileModule sample is not supported in dotnet

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Entropy#97]
Dnx used to support CompileModule but after moving to dotnet I believe it is going away or at least it's not currently clear what the plan will be. This affects the `Project.CompileModule` sample so once we find out whether the support will be available we need to update or remove this sample.

cc @muratg @davidfowl

**Comment by muratg** [comment]
Should we remove this sample?

**Comment by davidfowl** [comment]
Yep

**Comment by Tragetaschen** [comment]
*sob*

**Comment by davidfowl** [comment]
@Tragetaschen the best we can do here is offer an alternate compiler with the old dnx roslyn compiler that supported compile modules. But we're not going to ship that as "the thing". Roslyn is eventually going to support generators.

**Comment by Tragetaschen** [comment]
Na, no worries. I'm half-way through the restructuring already. The hardest part was the reflection bits, but these are now isolated from the code generation.

I know it's a bit specific to my environment, but all my generated code was already hidden behind interfaces and it only surfaced at DI container setup. I already had empty stub classes so that IntelliSense (the design time host) would not barf at me. That means my project compiles even without the `ICompileModule` and I can just run the project itself as the code generator. This immediately gives me all required assemblies to do "classic" reflection.

Maybe this helps others facing similar restructurings.

**Comment by muratg** [comment]
@ryanbrandenburg Could you remove this sample when you have some time?

**Comment by JunTaoLuo** [comment]
I have it as part of https://github.com/aspnet/Entropy/pull/98

**Comment by ryanbrandenburg** [comment]
Reassigning to @JunTaoLuo since he's already completed the work.

**Comment by JunTaoLuo** [comment]
merged in #98
